In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
store=pd.read_csv(r"C:\Users\TharunMahendra\OneDrive\Desktop\NIT\Superstore_Orders.csv")

In [4]:
id(store) #adress of memeory allocation

2510755011120

In [5]:
pd.set_option('display.max_colwidth',15) #max columnswidth to displayed set to 10 to display less matter 
pd.set_option('display.width',1)
(store)

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supp...,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,Message Boo...,Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supp...,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standar...,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supp...,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supp...,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltl...,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supp...,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Li...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supp...,New York City,United States,Patrick O'D...,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supp...,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding...,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supp...,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubb...,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'D...,Other,30-12-2023,US-2023-143259,10009,Gear Head A...,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supp...,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,Prince Edwa...,Binders,0.2,-0.6048,3,3.024

In [6]:
len(store) #no.of rows

10194

In [7]:
store.shape #rows,columns

(10194, 19)

In [8]:
store.columns #column names

Index(['Category',
       'City',
       'Country/Region',
       'Customer Name',
       'Manufacturer',
       'Order Date',
       'Order ID',
       'Postal Code',
       'Product Name',
       'Region',
       'Segment',
       'Ship Date',
       'Ship Mode',
       'State/Province',
       'Sub-Category',
       'Discount',
       'Profit',
       'Quantity',
       'Sales'],
      dtype='object')

In [9]:
len(store.columns)

19

In [10]:
store.isnull()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
store.isnull().sum()

Category          0
City              0
Country/Region    0
Customer Name     0
Manufacturer      0
Order Date        0
Order ID          0
Postal Code       0
Product Name      0
Region            0
Segment           0
Ship Date         0
Ship Mode         0
State/Province    0
Sub-Category      0
Discount          0
Profit            0
Quantity          0
Sales             0
dtype: int64

In [12]:
store[:]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supp...,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,Message Boo...,Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supp...,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standar...,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supp...,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supp...,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltl...,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supp...,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Li...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supp...,New York City,United States,Patrick O'D...,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supp...,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding...,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supp...,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubb...,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'D...,Other,30-12-2023,US-2023-143259,10009,Gear Head A...,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supp...,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,Prince Edwa...,Binders,0.2,-0.6048,3,3.024

In [13]:
store[0:10]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supp...,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,Message Boo...,Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supp...,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standar...,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supp...,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supp...,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltl...,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supp...,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Li...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Delu...,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
6,Office Supp...,Henderson,United States,Maria Etezadi,Rogers,06-01-2020,US-2020-167199,42420,Rogers Hand...,South,Home Office,10-01-2020,Standard Class,Kentucky,Art,0.0,1.4796,2,5.480
7,Office Supp...,Athens,United States,Jack O'Briant,Dixon,06-01-2020,US-2020-106054,30605,Dixon Prang...,South,Corporate,07-01-2020,First Class,Georgia,Art,0.0,5.2398,3,12.780
8,Office Supp...,Henderson,United States,Maria Etezadi,Ibico,06-01-2020,US-2020-167199,42420,Ibico Hi-Te...,South,Home Office,10-01-2020,Standard Class,Kentucky,Binders,0.0,274.4910,2,609.980
9,Office Supp...,Henderson,United States,Maria Etezadi,Alliance,06-01-2020,US-2020-167199,42420,Alliance Su...,South,Home Office,10-01-2020,Standard Class,Kentucky,Fasteners,0.0,0.3112,4,31.120

In [14]:
store[0:20:5]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supp...,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,Message Boo...,Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Delu...,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
10,Office Supp...,Henderson,United States,Maria Etezadi,Southworth,06-01-2020,US-2020-167199,42420,Southworth ...,South,Home Office,10-01-2020,Standard Class,Kentucky,Paper,0.0,3.0084,1,6.540
15,Office Supp...,Huntsville,United States,Vivek Sunda...,Acco,07-01-2020,US-2020-105417,77340,Acco Four P...,Central,Consumer,12-01-2020,Standard Class,Texas,Binders,0.8,-18.2525,7,10.430

In [15]:
store.head() #top 5 rows

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supp...,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,Message Boo...,Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supp...,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standar...,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supp...,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supp...,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltl...,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supp...,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Li...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536

In [16]:
store.head(3) #top 3

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supp...,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,Message Boo...,Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supp...,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standar...,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supp...,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784

In [17]:
store.tail() # bottom 5 rows

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10189,Office Supp...,New York City,United States,Patrick O'D...,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supp...,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding...,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supp...,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubb...,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'D...,Other,30-12-2023,US-2023-143259,10009,Gear Head A...,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supp...,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,Prince Edwa...,Binders,0.2,-0.6048,3,3.024

In [18]:
store.tail(3) #bottom 3

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10191,Office Supp...,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubb...,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'D...,Other,30-12-2023,US-2023-143259,10009,Gear Head A...,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supp...,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jone...,East,Consumer,03-01-2024,Standard Class,Prince Edwa...,Binders,0.2,-0.6048,3,3.024