In [1]:
import pandas as pd

In [2]:
store=pd.read_csv(r"C:\Users\TharunMahendra\OneDrive\Desktop\NIT\Datasets\Superstore_Orders.csv")

In [3]:
store.describe() #Generate descriptive statistics.

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

In [4]:
store.head()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536

### Splitting data

In [5]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [6]:
store['City']

0              Houston
1           Naperville
2           Naperville
3           Naperville
4         Philadelphia
             ...
10189    New York City
10190        Fairfield
10191         Loveland
10192    New York City
10193    Charlottetown
Name: City, Length: 10194, dtype: object

In [7]:
store[['City','Customer Name']]

                City      Customer Name
0            Houston      Darren Powers
1         Naperville      Phillina Ober
2         Naperville      Phillina Ober
3         Naperville      Phillina Ober
4       Philadelphia         Mick Brown
...              ...                ...
10189  New York City  Patrick O'Donnell
10190      Fairfield         Erica Bern
10191       Loveland      Jill Matthias
10192  New York City  Patrick O'Donnell
10193  Charlottetown        Harry Olson

[10194 rows x 2 columns]

In [8]:
store[['Category','City','Customer Name']]

              Category           City      Customer Name
0      Office Supplies        Houston      Darren Powers
1      Office Supplies     Naperville      Phillina Ober
2      Office Supplies     Naperville      Phillina Ober
3      Office Supplies     Naperville      Phillina Ober
4      Office Supplies   Philadelphia         Mick Brown
...                ...            ...                ...
10189  Office Supplies  New York City  Patrick O'Donnell
10190  Office Supplies      Fairfield         Erica Bern
10191  Office Supplies       Loveland      Jill Matthias
10192       Technology  New York City  Patrick O'Donnell
10193  Office Supplies  Charlottetown        Harry Olson

[10194 rows x 3 columns]

In [9]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [10]:
store_categoricaldata=store[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer','Order Date', 'Order ID', 'Postal Code', 
                             'Product Name', 'Region','Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category']]

In [11]:
store_categoricaldata

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders

In [12]:
store_categoricaldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
dtypes: object(15)
memory usage: 1.2+ MB

In [13]:
store_numericaldata=store[['Discount', 'Profit', 'Quantity', 'Sales']]

In [14]:
store

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [15]:
store_numericaldata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Discount  10194 non-null  float64
 1   Profit    10194 non-null  float64
 2   Quantity  10194 non-null  int64
 3   Sales     10194 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 318.7 KB

In [16]:
print(len(store.columns))
print(len(store_categoricaldata.columns))
print(len(store_numericaldata.columns))

19
15
4

In [17]:
store_categoricaldata.describe() #we dont find mean,min,max etc.. operations which performed on numerical data

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,3,542,2,800,183,1242,5111,655,1849,4,3,1338,4,59,17
top,Office Supplies,New York City,United States,William Brown,Other,05-09-2022,US-2023-100111,10035,Staples,West,Consumer,16-12-2021,Standard Class,California,Binders
freq,6128,915,9994,41,1940,38,14,263,50,3253,5281,38,6120,2001,1548

In [18]:
store_numericaldata.describe()

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000