# Split()
-     In Python, the split() method is used to divide a string into a list of substrings based on a specified delimiter.

In [1]:
text = "Python is fun"
result = text.split()
print(result)

['Python', 'is', 'fun']

#### Splitting using a specific character

In [2]:
text = "apple-banana-cherry"
result = text.split("-")
print(result)

['apple', 'banana', 'cherry']

#### Using max strings to split

In [3]:
text = "Python is great and powerful"
result = text.split(" ",3)
print(result)

['Python', 'is', 'great', 'and powerful']

## Splitting date & time

In [4]:
import pandas as pd
data = {'datetime': ['2025-03-26 & 14:15:00', '2025-03-27 & 09:30:00']}
df = pd.DataFrame(data)
df

                datetime
0  2025-03-26 & 14:15:00
1  2025-03-27 & 09:30:00

In [5]:
# Splitting date and time
df[['date', 'time']] = df['datetime'].str.split('&', expand=True)
df

                datetime         date       time
0  2025-03-26 & 14:15:00  2025-03-26    14:15:00
1  2025-03-27 & 09:30:00  2025-03-27    09:30:00

In [6]:
data = {'datetime': ['2025-03-26 14:15:00', '2025-03-27 09:30:00']}
df = pd.DataFrame(data)

# Convert the 'datetime' column to pandas datetime format
df['datetime'] = pd.to_datetime(df['datetime'])
# Extract individual components
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df['second'] = df['datetime'].dt.second

df

             datetime  year  month  day  hour  minute  second
0 2025-03-26 14:15:00  2025      3   26    14      15       0
1 2025-03-27 09:30:00  2025      3   27     9      30       0

### Splitting adress

In [7]:
data = {'address': ['123 Main St, New York, NY', '456 High St, Chicago, IL']}
df = pd.DataFrame(data)
df

                     address
0  123 Main St, New York, NY
1   456 High St, Chicago, IL

In [8]:
# Splitting address into components
df[['street', 'city', 'state']] = df['address'].str.split(',', expand=True)
df

                     address       street       city state
0  123 Main St, New York, NY  123 Main St   New York    NY
1   456 High St, Chicago, IL  456 High St    Chicago    IL

# Let's do on DataSet

In [9]:
data=pd.read_csv(r"C:\Users\TharunMahendra\OneDrive\Desktop\NIT\DataSets\Superstore_Orders.csv")

In [10]:
data.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [11]:
data=data.drop(['Category', 'Manufacturer','Order ID','Segment', 'Ship Date', 'Ship Mode','City','Product Name','Sub-Category','Discount', 'Profit', 'Quantity', 'Sales'],axis=1)
data.head()

,Country/Region,Customer Name,Order Date,Postal Code,Region,State/Province
0,United States,Darren Powers,03-01-2020,77015,Central,Texas
1,United States,Phillina Ober,04-01-2020,60540,Central,Illinois
2,United States,Phillina Ober,04-01-2020,60540,Central,Illinois
3,United States,Phillina Ober,04-01-2020,60540,Central,Illinois
4,United States,Mick Brown,05-01-2020,19143,East,Pennsylvania

In [12]:
data[['date','month','year']]=data['Order Date'].str.split('-',expand=True)

In [13]:
data.head(20)

,Country/Region,Customer Name,Order Date,Postal Code,Region,State/Province,date,month,year
0,United States,Darren Powers,03-01-2020,77015,Central,Texas,03,01,2020
1,United States,Phillina Ober,04-01-2020,60540,Central,Illinois,04,01,2020
2,United States,Phillina Ober,04-01-2020,60540,Central,Illinois,04,01,2020
3,United States,Phillina Ober,04-01-2020,60540,Central,Illinois,04,01,2020
4,United States,Mick Brown,05-01-2020,19143,East,Pennsylvania,05,01,2020
5,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
6,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
7,United States,Jack O'Briant,06-01-2020,30605,South,Georgia,06,01,2020
8,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
9,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
10,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
11,United States,Lycoris Saunders,06-01-2020,90049,West,California,06,01,2020
12,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
13,United States,Maria Etezadi,06-01-2020,42420,South,Kentucky,06,01,2020
14,United States,Vivek Sundaresam,07-01-2020,77340,Central,Texas,07,01,2020
15,United States,Vivek Sundaresam,07-01-2020,77340,Central,Texas,07,01,2020
16,United States,Melanie Seite,09-01-2020,78041,Central,Texas,09,01,2020
17,United States,Melanie Seite,09-01-2020,78041,Central,Texas,09,01,2020
18,United States,Anthony Jacobs,10-01-2020,22153,South,Virginia,10,01,2020
19,United States,Anthony Jacobs,10-01-2020,22153,South,Virginia,10,01,2020