In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\TharunMahendra\OneDrive\Desktop\NIT\DataSets\Country_GDP_data.csv")

In [3]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [5]:
len(df)

195

In [6]:
df.shape

(195, 5)

In [7]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
len(df.columns)

5

In [10]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [11]:
df.tail()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [12]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

#### Transpose()

In [13]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
BirthRate,195.0,21.469928,10.605467,7.9,12.1205,19.68,29.7595,49.6610
InternetUsers,195.0,42.076471,29.030788,0.9,14.5200,41.00,66.2250,96.5468

#### changing column names

In [15]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [16]:
df.columns=['a','b','c','d','e']

In [17]:
df.head(1)

       a    b       c     d            e
0  Aruba  ABW  10.244  78.9  High income

In [18]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [19]:
df.columns=['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup']

In [20]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [21]:
df.head(1)

  CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0       Aruba         ABW     10.244           78.9  High income

In [22]:
df.dtypes

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

## Slicing on dataframe

#### rows

In [23]:
df[:] #all rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [24]:
df[0:10] #top 10 rows

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [25]:
df[10:] #10 to lasttt

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
10,Azerbaijan,AZE,18.300,58.7000,Upper middle income
11,Burundi,BDI,44.151,1.3000,Low income
12,Belgium,BEL,11.200,82.1702,High income
13,Benin,BEN,36.440,4.9000,Low income
14,Burkina Faso,BFA,40.551,9.1000,Low income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
191,South Africa,ZAF,20.850,46.5000,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income
193,Zambia,ZMB,40.471,15.4000,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5000,Low income

In [26]:
df[::50] #every 50th row

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244      78.900000          High income
50      Ecuador         ECU     21.070      40.353684  Upper middle income
100       Libya         LBY     21.425      16.500000  Upper middle income
150       Sudan         SDN     33.477      22.700000  Lower middle income

In [27]:
df[::-1] #reverse

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

#### columns

In [28]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [29]:
df['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [30]:
df[['CountryName','CountryCode']]

              CountryName CountryCode
0                   Aruba         ABW
1             Afghanistan         AFG
2                  Angola         AGO
3                 Albania         ALB
4    United Arab Emirates         ARE
..                    ...         ...
190           Yemen, Rep.         YEM
191          South Africa         ZAF
192      Congo, Dem. Rep.         COD
193                Zambia         ZMB
194              Zimbabwe         ZWE

[195 rows x 2 columns]

In [31]:
df[['CountryName','CountryCode','IncomeGroup']]

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

#### lets combine both

In [32]:
df[::25][['CountryName','InternetUsers']] #every 25th row;both columns

    CountryName  InternetUsers
0         Aruba      78.900000
25     Barbados      73.000000
50      Ecuador      40.353684
75     Honduras      17.800000
100       Libya      16.500000
125     Namibia      13.900000
150       Sudan      22.700000
175     Tunisia      43.800000

In [33]:
df[::50][['BirthRate','IncomeGroup']]

     BirthRate          IncomeGroup
0       10.244          High income
50      21.070  Upper middle income
100     21.425  Upper middle income
150     33.477  Lower middle income

## Mathametical Operations

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [35]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [36]:
print(df['CountryName']+"====="+df['IncomeGroup']) #we can add two object type data but we cant concatenate

0                     Aruba=====High income
1                Afghanistan=====Low income
2            Angola=====Upper middle income
3           Albania=====Upper middle income
4      United Arab Emirates=====High income
                       ...
190     Yemen, Rep.=====Lower middle income
191    South Africa=====Upper middle income
192         Congo, Dem. Rep.=====Low income
193          Zambia=====Lower middle income
194                 Zimbabwe=====Low income
Length: 195, dtype: object

In [37]:
df['BirthRate']*df['InternetUsers']

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [38]:
df['BirthRate']+df['InternetUsers']

0      89.144
1      41.153
2      65.085
3      70.077
4      99.044
        ...
190    52.947
191    67.350
192    44.594
193    55.871
194    54.215
Length: 195, dtype: float64

## Modifying data

#### adding column

In [39]:
 df['newcol']=df['BirthRate']*df['InternetUsers']

In [40]:
df[0:2]

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup    newcol
0        Aruba         ABW     10.244           78.9  High income  808.2516
1  Afghanistan         AFG     35.253            5.9   Low income  207.9927

#### removing column

In [41]:
df.drop('newcol',axis=1) #axis=1 indicates column

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [42]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup    newcol
0        Aruba         ABW     10.244           78.9  High income  808.2516
1  Afghanistan         AFG     35.253            5.9   Low income  207.9927

In [43]:
df=df.drop('newcol',axis=1) # to remove permanently

In [44]:
df.head(2)

   CountryName CountryCode  BirthRate  InternetUsers  IncomeGroup
0        Aruba         ABW     10.244           78.9  High income
1  Afghanistan         AFG     35.253            5.9   Low income

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [46]:
df.BirthRate

0      10.244
1      35.253
2      45.985
3      12.877
4      11.044
        ...
190    32.947
191    20.850
192    42.394
193    40.471
194    35.715
Name: BirthRate, Length: 195, dtype: float64

In [47]:
df.BirthRate<15 #lessthan

0       True
1      False
2      False
3       True
4       True
       ...
190    False
191    False
192    False
193    False
194    False
Name: BirthRate, Length: 195, dtype: bool

In [48]:
filter=df.BirthRate>15

In [49]:
filter

0      False
1       True
2       True
3      False
4      False
       ...
190     True
191     True
192     True
193     True
194     True
Name: BirthRate, Length: 195, dtype: bool

In [50]:
df[filter].count() #70 true rows

CountryName      124
CountryCode      124
BirthRate        124
InternetUsers    124
IncomeGroup      124
dtype: int64

In [51]:
df[filter] #it prints the fitered values

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
5,Argentina,ARG,17.716,59.9,High income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
10,Azerbaijan,AZE,18.300,58.7,Upper middle income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [52]:
filter2=df['BirthRate']<100

In [53]:
filter2

0      True
1      True
2      True
3      True
4      True
       ...
190    True
191    True
192    True
193    True
194    True
Name: BirthRate, Length: 195, dtype: bool

In [54]:
df[filter&filter2] #greater than 15 less than 100

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
5,Argentina,ARG,17.716,59.9,High income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
10,Azerbaijan,AZE,18.300,58.7,Upper middle income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [55]:
df[(df.BirthRate>30)& (df.InternetUsers>10)]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
63,Ghana,GHA,33.131,12.3,Lower middle income
65,"Gambia, The",GMB,42.525,14.0,Low income
67,Equatorial Guinea,GNQ,35.362,16.4,High income
91,Kenya,KEN,35.194,39.0,Lower middle income
128,Nigeria,NGA,40.045,38.0,Lower middle income
150,Sudan,SDN,33.477,22.7,Lower middle income
151,Senegal,SEN,38.533,13.1,Lower middle income
158,South Sudan,SSD,37.126,14.1,Low income
159,Sao Tome and Principe,STP,34.537,23.0,Lower middle income
164,Swaziland,SWZ,30.093,24.7,Lower middle income
170,Tajikistan,TJK,30.792,16.0,Lower middle income
178,Uganda,UGA,43.474,16.2,Low income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [56]:
df[df.IncomeGroup=='Low income']

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90,Low income
11,Burundi,BDI,44.151,1.30,Low income
13,Benin,BEN,36.440,4.90,Low income
14,Burkina Faso,BFA,40.551,9.10,Low income
29,Central African Republic,CAF,34.076,3.50,Low income
38,Comoros,COM,34.326,6.50,Low income
52,Eritrea,ERI,34.800,0.90,Low income
55,Ethiopia,ETH,32.925,1.90,Low income
64,Guinea,GIN,37.337,1.60,Low income
65,"Gambia, The",GMB,42.525,14.00,Low income
66,Guinea-Bissau,GNB,37.503,3.10,Low income
77,Haiti,HTI,25.345,10.60,Low income
93,Cambodia,KHM,24.462,6.80,Low income
99,Liberia,LBR,35.521,3.20,Low income
111,Madagascar,MDG,34.686,3.00,Low income
115,Mali,MLI,44.138,3.50,Low income
120,Mozambique,MOZ,39.705,5.40,Low income
123,Malawi,MWI,39.459,5.05,Low income
127,Niger,NER,49.661,1.70,Low income
132,Nepal,NPL,20.923,13.30,Low income
148,Rwanda,RWA,32.689,9.00,Low income
154,Sierra Leone,SLE,36.729,1.70,Low income
156,Somalia,SOM,43.891,1.50,Low income
158,South Sudan,SSD,37.126,14.10,Low income
167,Chad,TCD,45.745,2.30,Low income
168,Togo,TGO,36.080,4.50,Low income
177,Tanzania,TZA,39.518,4.40,Low income
178,Uganda,UGA,43.474,16.20,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.20,Low income
194,Zimbabwe,ZWE,35.715,18.50,Low income

In [57]:
len(df[df.IncomeGroup=='Low income'])

30

#### to get unique categories

In [58]:
df.IncomeGroup.unique()

array(['High income', 'Low income', 'Upper middle income',
       'Lower middle income'], dtype=object)